### ISSUE TITLE
直接修改CMAKE_${LANG}_FLAGS_MINSIZEREL_INIT无效

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/cmake-tools#1]
根据我的测试，直接修改`CMAKE_C_FLAGS_MINSIZEREL_INIT`和`CMAKE_CXX_FLAGS_MINSIZEREL_INIT`是不管用的，生成的Makefile里还是`-O1`，没有变成`-Xclang -Oz`。

我自己的做法是直接替换`CMAKE_${LANG}_FLAGS_MINSIZEREL`中的参数：`string(REGEX REPLACE "[-|/]O[1|s]" "-Xclang -Oz" CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL}")`，这样做是有效的。

**Comment by wang-bin** [comment]
清除cmake缓存了没？

**Comment by wangwenx190** [comment]
是全新构建的，根本没有缓存

**Comment by wang-bin** [comment]
测了下不加-O1只有-Oz还是会比较大，只有两个都有才最小

**Comment by wang-bin** [comment]
拉下最新的试试

**Comment by wangwenx190** [comment]
为大小优化+LTO大小是最小的，开了LTO能更小一点

**Comment by wang-bin** [comment]
windows的lto?之前测了不是增大了么

**Comment by wangwenx190** [comment]
为大小优化+LTO=尽可能小
为速度优化+LTO=尽可能大
这是我测试得出的结论，stackoverflow上也有人有类似的说法

**Comment by wang-bin** [comment]
有链接不？

**Comment by wang-bin** [comment]
lto我测出来还是大了一点

**Comment by wangwenx190** [comment]
之前我测的时候没有把Oz和LTO同时开启过，而clang-cl默认优化级别是O2，所以之前我测的都是O2+LTO，所以文件反而变得很大。这和vc完全不一样，vc只要开了LTCG文件就会变小，那个时候我以为clang也是这样。后来我自己单独编译qtbase做实验，发现使用Oz优化但不开始LTO会小很多，Oz优化同时开启LTO能再小一些，有MB级别的差别，所以效果还是挺明显的。我用了控制变量法，实验结果还是有保证的。由于这都是好几周之前的事了，链接也没保存，一时半会估计也找不到，就先不发了。

**Comment by wangwenx190** [comment]
这么奇怪吗？每次我用qtbase得出的结论都和您不太一样。

**Comment by wangwenx190** [comment]
之前我和英特尔的大佬讨论的时候他还一直在怀疑“为大小优化+LTO的意义”，哈哈

**Comment by wang-bin** [comment]
我编译mdk的相关的参数及结果

下面两组lto变大
- -Xclang -Oz -O1 -flto=thin: 538K
- -Xclang -Oz -O1: 534k
- -O1 -flto=thin: 613K
- -O1: 597K

下面这组lto变小
- -Xclang -Oz -flto=thin: 545K
- -Xclang -Oz: 594K

结论是-Xclang -O1无lto最小

**Comment by wangwenx190** [comment]
好的，我用您的方案再测一下

**Comment by wangwenx190** [comment]
我用我自己的一个小项目测试了一下，下面是结果：

| 方案编号 | 优化参数 | 文件大小[dll, exe] |
| ---------- | ---------- | ------------------- |
| 1 | /O1 | 23 KB, 36 KB |
| 2 | /O1 -flto=thin | 23 KB, 36 KB |
| 3 | /O1 -Xclang -Oz | 22 KB, 35 KB |
| 4 | /O1 -Xclang -Oz -flto=thin | 21 KB, 35 KB |
| 5 | -Xclang -Oz | 22 KB, 35 KB |
| 6 | -Xclang -Oz -flto=thin | 21 KB, 35 KB |

由以上测试结果再结合我之前多次编译qtbase的经历可以得出，`/O1 -Xclang -Oz`一定会是文件最小的方案；`-flto=thin`这个参数有很大的不确定性，有时会使文件变小，有时会使文件增大，但整体上是符合“**为大小优化时使文件尽可能的小，为速度优化时使文件尽可能的大**”这个规律。

**Comment by wangwenx190** [comment]
但用您的脚本在**Windows**上仍然无法将`/O1`替换为`-Xclang -Oz`，我用的是**Ninja**，跟这个有关系吗？肯定不是缓存的原因，每次构建前我都会将构建目录删除的，每次都是干净的构建。

**Comment by wang-bin** [comment]
> 但用您的脚本在Windows上仍然无法将/O1替换为-Xclang -Oz，我用的是Ninja，跟这个有关系吗

没关系，ninja makefile都正确，在win、mac、linux上都测了

**Comment by wangwenx190** [comment]
那我先关了这个issue，有问题再重新打开

**Comment by wang-bin** [comment]
-Oz 和-O1一起用可能会有问题，x86 32位我碰到了崩溃，自己编译的angle崩溃可能也是这个导致的，具体崩溃原因没查

**Comment by wangwenx190** [comment]
还是不要同时使用这两个参数了吧，一起用实在是太奇怪了

**Comment by wang-bin** [comment]
恩，后面我更新下

**Comment by wangwenx190** [comment]
我大概知道为什么`CMAKE_CXX_FLAGS_MINSIZEREL_INIT`没有生效了，我用的是VS提供的CMake和Ninja，版本都特别老，是好多年前的版本，估计就是这个的锅。我在Linux上测试您的脚本确实没问题。
