### ISSUE TITLE
[Bug] windows上的target设置有问题

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/cmake-tools#2]
https://github.com/wang-bin/cmake-tools/blob/419b622feed8768593edad85f78eac8518e8baf7/windows.clang.cmake#L184

这一行设置的target有问题。我写的程序在连接Qt静态库时会报非常多的警告，说程序的target是**x86_64-unknown-windows-msvc**，与Qt库的**x86_64-pc-windows-msvc**不匹配。正常的target是**x86_64-pc-windows-msvc**，您落下了一个`-pc-`。其实编译程序是没问题的，但有些情况会出现大量警告，不好看。

**Comment by wang-bin** [comment]
qt在哪里设置的？我没找到

**Comment by wang-bin** [comment]
clang 8.0才开始检查target的，感觉检查vendor有点多余

**Comment by wangwenx190** [comment]
qt没设置target，但使用clang-cl编译默认就会设置`x86_64-pc-windows-msvc`这个target，使用`clang-cl --version`就能看到

**Comment by wang-bin** [comment]
已改

**Comment by wangwenx190** [comment]
多谢。麻烦您了。
