### ISSUE TITLE
[Feature request] 添加一个可以启用LTO的选项

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/cmake-tools#3]
现在我都是在自己的CMakeLists.txt里开启LTO的，能不能直接提供一个option来启用LTO？

**Comment by wang-bin** [comment]
USE_LTO=0,1,N,thin，在tools.cmake

**Comment by wangwenx190** [comment]
但是windows.clang.cmake和linux.clang.cmake都没有包含这个文件，要我在自己的工程里手动包含这个文件吗？

**Comment by wang-bin** [comment]
对

**Comment by wangwenx190** [comment]
好的，明白了。

**Comment by wangwenx190** [comment]
要是能在README里提一下就好了

**Comment by wangwenx190** [comment]
README里有，刚看到，是我的锅，不好意思
