### ISSUE TITLE
macOS和Android支持的问题？

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/cmake-tools#6]
这个repo的描述里提到还支持macOS和Android，但这个repo里明显没有这两个平台相关的cmake脚本啊，是描述有误还是暂时还没有添加相关的脚本？

**Comment by wang-bin** [comment]
mac不需要，android 用ndk自带的就行，这边做了些额外的处理，比如老的ndk使用非系统stl时避免链接道不必要的库、一个项木同时支持链接shared和static的stl的target，这些我给ndk提过最新的ndk基本都支持了

**Comment by wangwenx190** [comment]
OK
