### ISSUE TITLE
拼写错误导致调用了错误的宏

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/cmake-tools#7]
https://github.com/wang-bin/cmake-tools/blob/1f90c038569d26474bb53fd09d9cad12528cc3d9/add_flags.cmake#L35
第35行语句所属的宏是用来添加`CMAKE_C_FLAGS`的，怎么调用了`add_cxx_flags`这个宏？

**Comment by wangwenx190** [comment]
https://github.com/wang-bin/cmake-tools/blob/1f90c038569d26474bb53fd09d9cad12528cc3d9/add_flags.cmake#L27
这一行明明是添加`CMAKE_C_FLAGS`，怎么双引号里又变成了`CMAKE_CXX_FLAGS`？

**Comment by wang-bin** [comment]
已修，谢谢
